version: "3.8"
services:
  api:
    build: .
    container_name: preopen-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - APP_CONFIG_PATH=/app/config/config.yaml
      - PREOPEN_JSON_LOGS=1
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
    restart: unless-stopped
